

services:
    astro_backend:
      build: 
        context: .
        dockerfile: Dockerfile.prod
      command: gunicorn space.wsgi:application --bind 0.0.0.0:8000
      ports:
        - "8000:8000"
      env_file:
        - .env.prod 
      depends_on:
        - db
      environment:
        - APP_HOME=/home/app/astro_backend  
      
      networks:
        - astro_network

    db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - .env.prod.dbms    
      networks:
        - astro_network

    nginx:
      build: ./nginx
      ports:
        - 1337:80
      depends_on:
        - astro_backend    


volumes:
  postgres_data:

networks:
  astro_network:
    driver: bridge  